-- Placeholder file — migration 019 was not created (skipped).
-- History: 015 created indexes, 020 adds bilingual content columns.
-- This file exists only to maintain sequential numbering for migration tools.
